version: '3.8'
services:
  database:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_DB=test_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root
    ports:
      - '5432:5432'
    volumes: 
      - ./postgress_data:/var/lib/postgresql/data
